import { ChromaLayerState, CanvasSettings, VectorLayerResult } from '../engine/types';
import { getPrintableArea, generateRegistrationMarksSVG } from '../engine/layout/canvasLayout';

export interface SVGExportOptions {
  strokeOnly?: boolean;
  strokeColor?: string;
  strokeWidthMm?: number;
  includeRegistrationMarks?: boolean;
}

/**
 * Generates unit-accurate Master Combined Multi-Color SVG with full physical sheet dimensions
 */
export function generateMasterCombinedSVG(
  layers: ChromaLayerState[],
  vectorResults: Map<string, VectorLayerResult>,
  canvas: CanvasSettings,
  options: SVGExportOptions = {},
  processingDimensions?: { width: number; height: number }
): string {
  const { widthMm, heightMm, widthPx, heightPx, pxPerMm } = getPrintableArea(canvas);
  const viewW = processingDimensions?.width || widthPx;
  const viewH = processingDimensions?.height || heightPx;

  const isStrokeOnly = !!options.strokeOnly;
  const strokeColor = options.strokeColor || '#000000';
  const strokeWidth = options.strokeWidthMm ? `${options.strokeWidthMm * pxPerMm}px` : '0.5px';

  // Sort layers from bottom Z (0) to top Z (N-1)
  const sortedLayers = [...layers].sort((a, b) => a.order - b.order);

  const layerGroups = sortedLayers.map((layer, index) => {
    const isLayer0 = layer.order === 0;
    const isVoid = isLayer0 && layer.isSolidBacking === false;
    if (isVoid) {
      return '';
    }

    const isSolid = isLayer0 && layer.isSolidBacking !== false;
    const vec = vectorResults.get(layer.id);
    const pathData = isSolid ? `M 0 0 H ${viewW} V ${viewH} H 0 Z` : (vec?.pathData || '');
    if (!pathData) return '';

    const sanitizedName = layer.swatch.name.replace(/[^a-zA-Z0-9_-]/g, '_');
    const groupId = `layer_${String(index + 1).padStart(2, '0')}_${sanitizedName}`;

    const fillAttr = isStrokeOnly ? 'none' : layer.swatch.hex;
    const strokeAttr = isStrokeOnly ? strokeColor : 'none';
    const strokeWidthAttr = isStrokeOnly ? `stroke-width="${strokeWidth}"` : '';

    return `  <!-- Layer ${index + 1}: ${layer.swatch.name} (${layer.swatch.hex}) -->
  <g id="${groupId}" inkscape:label="${layer.swatch.name}" inkscape:groupmode="layer">
    <path
      d="${pathData}"
      fill="${fillAttr}"
      fill-rule="evenodd"
      stroke="${strokeAttr}"
      ${strokeWidthAttr}
    />
  </g>`;
  }).filter(Boolean).join('\n');

  const regMarks = options.includeRegistrationMarks
    ? `\n  <!-- Registration Marks -->\n  <g id="registration_marks">\n    <path d="${generateRegistrationMarksSVG(canvas, viewW, viewH)}" stroke="#000000" stroke-width="0.8" fill="none" />\n  </g>`
    : '';

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
  width="${widthMm}mm"
  height="${heightMm}mm"
  viewBox="0 0 ${viewW} ${viewH}"
  version="1.1"
>
  <title>CutUp Chroma Master Cut Pattern</title>
  <desc>Generated by CutUp Chroma - Physical Perceptual Color Vector Workstation</desc>
${layerGroups}${regMarks}
</svg>`;
}

/**
 * Generates an isolated single-layer vector cut SVG with full physical sheet dimensions
 */
export function generateSingleLayerSVG(
  layer: ChromaLayerState,
  vectorResult: VectorLayerResult | undefined,
  canvas: CanvasSettings,
  options: SVGExportOptions = {},
  processingDimensions?: { width: number; height: number }
): string {
  const { widthMm, heightMm, widthPx, heightPx, pxPerMm } = getPrintableArea(canvas);
  const viewW = processingDimensions?.width || widthPx;
  const viewH = processingDimensions?.height || heightPx;

  const isLayer0 = layer.order === 0;
  const isVoid = isLayer0 && layer.isSolidBacking === false;
  if (isVoid) {
    return '';
  }

  const isSolid = isLayer0 && layer.isSolidBacking !== false;
  const pathData = isSolid ? `M 0 0 H ${viewW} V ${viewH} H 0 Z` : (vectorResult?.pathData || '');

  const isStrokeOnly = options.strokeOnly !== false;
  const strokeColor = options.strokeColor || '#000000';
  const strokeWidth = options.strokeWidthMm ? `${options.strokeWidthMm * pxPerMm}px` : '0.5px';
  const fillAttr = isStrokeOnly ? 'none' : layer.swatch.hex;

  const regMarks = options.includeRegistrationMarks
    ? `\n  <!-- Registration Marks -->\n  <g id="registration_marks">\n    <path d="${generateRegistrationMarksSVG(canvas, viewW, viewH)}" stroke="#000000" stroke-width="0.8" fill="none" />\n  </g>`
    : '';

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="${widthMm}mm"
  height="${heightMm}mm"
  viewBox="0 0 ${viewW} ${viewH}"
  version="1.1"
>
  <title>Layer: ${layer.swatch.name} (${layer.swatch.hex})</title>
  <desc>CutUp Chroma Layer ${layer.order + 1} - Color: ${layer.swatch.name}</desc>
  <g id="cut-paths" fill="${fillAttr}" fill-rule="evenodd" stroke="${strokeColor}" stroke-width="${strokeWidth}">
    <path d="${pathData}" />
  </g>${regMarks}
</svg>`;
}
