import { ChromaLayerState, CanvasSettings, VectorLayerResult } from '../engine/types';
import { getPrintableArea, generateRegistrationMarksSVG } from '../engine/layout/canvasLayout';

export interface SVGExportOptions {
  strokeOnly?: boolean;
  strokeColor?: string;
  strokeWidthMm?: number;
  includeRegistrationMarks?: boolean;
  mirrorHorizontal?: boolean;
  solidBlack?: boolean;
}

/**
 * Generates unit-accurate Master Combined Multi-Color SVG with full physical sheet dimensions
 */
export function generateMasterCombinedSVG(
  layers: ChromaLayerState[],
  vectorResults: Map<string, VectorLayerResult>,
  canvas: CanvasSettings,
  options: SVGExportOptions = {},
  processingDimensions?: { width: number; height: number }
): string {
  const { widthMm, heightMm, widthPx, heightPx, pxPerMm } = getPrintableArea(canvas);
  const viewW = processingDimensions?.width || widthPx;
  const viewH = processingDimensions?.height || heightPx;

  const isStrokeOnly = !!options.strokeOnly;
  const strokeColor = options.strokeColor || '#000000';
  const strokeWidth = options.strokeWidthMm ? `${options.strokeWidthMm * pxPerMm}px` : '0.5px';

  // Sort layers from bottom Z (0) to top Z (N-1)
  const sortedLayers = [...layers].sort((a, b) => a.order - b.order);

  const layerGroups = sortedLayers.map((layer, index) => {
    const isLayer0 = layer.order === 0;
    const isVoid = isLayer0 && layer.isSolidBacking === false;
    if (isVoid) {
      return '';
    }

    const isSolid = isLayer0 && layer.isSolidBacking !== false;
    const vec = vectorResults.get(layer.id);
    const pathData = vec?.pathData || (isSolid ? `M 0 0 H ${viewW} V ${viewH} H 0 Z` : '');
    if (!pathData) return '';

    const groupId = `layer_${String(index).padStart(2, '0')}_${index === 0 ? 'Base' : 'Layer'}`;

    const fillColor = options.solidBlack ? '#000000' : layer.swatch.hex;
    const layerStrokeColor = options.strokeColor || (options.solidBlack ? '#000000' : layer.swatch.hex);
    const fillAttr = isStrokeOnly ? 'none' : fillColor;
    const strokeAttr = isStrokeOnly ? layerStrokeColor : 'none';
    const strokeWidthAttr = isStrokeOnly ? `stroke-width="${strokeWidth}"` : '';

    return `  <!-- Layer ${index}${index === 0 ? ' (Base Foundation)' : ''}: ${layer.swatch.hex} -->
  <g id="${groupId}" inkscape:label="${index === 0 ? 'Base Foundation' : `Layer ${index}`}" inkscape:groupmode="layer">
    <path
      d="${pathData}"
      fill="${fillAttr}"
      fill-rule="evenodd"
      stroke="${strokeAttr}"
      ${strokeWidthAttr}
    />
  </g>`;
  }).filter(Boolean).join('\n');

  const regMarks = options.includeRegistrationMarks
    ? `\n  <!-- Registration Marks -->\n  <g id="registration_marks">\n    <path d="${generateRegistrationMarksSVG(canvas, viewW, viewH)}" stroke="#000000" stroke-width="0.8" fill="none" />\n  </g>`
    : '';

  const mirrorWrapStart = options.mirrorHorizontal ? `  <g id="mirrored-content" transform="translate(${viewW}, 0) scale(-1, 1)">\n` : '';
  const mirrorWrapEnd = options.mirrorHorizontal ? `  </g>\n` : '';

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
  width="${widthMm}mm"
  height="${heightMm}mm"
  viewBox="0 0 ${viewW} ${viewH}"
  version="1.1"
>
  <title>CutUp Chroma Master Cut Pattern</title>
  <desc>Generated by CutUp Chroma - Physical Perceptual Color Vector Workstation</desc>
${mirrorWrapStart}${layerGroups}${mirrorWrapEnd}${regMarks}
</svg>`;
}

/**
 * Generates an isolated single-layer vector cut SVG with full physical sheet dimensions
 */
export function generateSingleLayerSVG(
  layer: ChromaLayerState,
  vectorResult: VectorLayerResult | undefined,
  canvas: CanvasSettings,
  options: SVGExportOptions = {},
  processingDimensions?: { width: number; height: number }
): string {
  const { widthMm, heightMm, widthPx, heightPx, pxPerMm } = getPrintableArea(canvas);
  const viewW = processingDimensions?.width || widthPx;
  const viewH = processingDimensions?.height || heightPx;

  const isLayer0 = layer.order === 0;
  const isVoid = isLayer0 && layer.isSolidBacking === false;
  if (isVoid) {
    return '';
  }

  const isSolid = isLayer0 && layer.isSolidBacking !== false;
  const pathData = vectorResult?.pathData || (isSolid ? `M 0 0 H ${viewW} V ${viewH} H 0 Z` : '');

  const isStrokeOnly = options.strokeOnly !== false;
  const strokeColor = options.strokeColor || '#000000';
  const strokeWidth = options.strokeWidthMm ? `${options.strokeWidthMm * pxPerMm}px` : '0.5px';
  const fillColor = options.solidBlack ? '#000000' : layer.swatch.hex;
  const fillAttr = isStrokeOnly ? 'none' : fillColor;

  const regMarks = options.includeRegistrationMarks
    ? `\n  <!-- Registration Marks -->\n  <g id="registration_marks">\n    <path d="${generateRegistrationMarksSVG(canvas, viewW, viewH)}" stroke="#000000" stroke-width="0.8" fill="none" />\n  </g>`
    : '';

  const mirrorWrapStart = options.mirrorHorizontal ? `  <g id="mirrored-content" transform="translate(${viewW}, 0) scale(-1, 1)">\n` : '';
  const mirrorWrapEnd = options.mirrorHorizontal ? `  </g>\n` : '';

  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="${widthMm}mm"
  height="${heightMm}mm"
  viewBox="0 0 ${viewW} ${viewH}"
  version="1.1"
>
  <title>Layer: ${layer.swatch.name} (${layer.swatch.hex})</title>
  <desc>CutUp Chroma Layer ${layer.order + 1} - Color: ${layer.swatch.name}</desc>
${mirrorWrapStart}  <g id="cut-paths" fill="${fillAttr}" fill-rule="evenodd" stroke="${strokeColor}" stroke-width="${strokeWidth}">
    <path d="${pathData}" />
  </g>
${mirrorWrapEnd}${regMarks}
</svg>`;
}
